# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-musl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-musl
  template:
    metadata:
      labels:
        app: python-flask-musl
    spec:
      containers:
      - name: python-flask-musl
        image: ghcr.io/averagenative/python-musl-flask:latest
        ports:
        - containerPort: 80
